version: "3"

services:
  db:
    image: postgres
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: "davical"

  app:
    image: tuxnvape/davical-standalone
    volumes:
      - davical_config:/config
    restart: always
    ports:
      - 80:80
    environment:
      HOST_NAME: "example.org"
      PGSQL_ROOT_PASS: "davical"
      PASSDAVDB: "davical"
      DBHOST: "db"
      ADMINDAVICALPASS: "admin"
      LANG: "fr_FR.UTF-8"
      LC_ALL: "fr_FR.UTF-8"
      DAVICAL_LANG: "fr_FR"
volumes:
  davical_config:
  pgsql_data:
