name: Build

on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push php8 version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.php8
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            tuxnvape/davical-standalone:latest
            tuxnvape/davical-standalone:8-1.1.10
 
            
      - name: Build and push php81 version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.php81
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            tuxnvape/davical-standalone:latest
            tuxnvape/davical-standalone:81-1.1.10
