name: Multiarch build

on:
  push:
      
env:
  IMAGE_NAME: tuxnvape/davical-standalone
  IMAGE_TAG: latest
  IMAGE_REGISTRY: darkregistry.infrarinox.net

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
          
      - name: Build image 
        id: build2-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: tuxnvape/docker-standalone
          tags: latest
          archs: amd64
          dockerfiles: |
            ./Dockerfile.php81
          
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: darkregistry.infrarinox.net
          username: ${{ secrets.ESTE_USER }}
          password: ${{ secrets.ESTE_PWD }}
          
      - name: Build and push php8 version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.php81
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            tuxnvape/davical-standalone:latest
